# Generated by Django 5.1.4 on 2025-04-03 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discount_price_product_discounted_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pardesh', 'Andhra Pardesh'), ('Arunchal Pardesh', 'Arunchal Pardesh'), ('Assam ', 'Assam'), ('Bihar', 'Bihar'), ('Chandighar', 'Chandighar'), ('Chattisghar', 'Chattisghar'), ('Dadea & Nagra Haveli', 'Dadea & Nagra Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pardesh', 'Himachal Pardesh'), ('jammu & Kashmir', 'jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnatak', 'Karnatak'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pardesh', 'Madhya Pardesh'), ('Maharashtra', 'Maharashtra'), ('ManiPur', 'ManiPur'), ('Meghalaya', 'Meghalaya'), ('Nahaland', 'Nahaland'), ('odisa', 'odisa'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajsthan', 'Rajsthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangna', 'Telangna'), ('UttaraKhand', 'UttaraKhand'), ('Utter Pardesh', 'Utter Pardesh'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
